
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { persistStore } from 'redux-persist';
import { store } from "../redux/store"
const inter = Inter({ subsets: ['latin'] })
let persistor = persistStore(store)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <Provider store ={store}>
      <PersistGate persistor={persistor}>
      {children}
    </PersistGate>
    </Provider></body>
    </html>
  )
}
